kind: Service
apiVersion: v1
metadata:
  name: lzh-service
spec:
  selector:
    app: lzh
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lzh
  labels:
    app: lzh
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lzh
  template:
    metadata:
      labels:
        app: lzh
    spec:
      imagePullSecrets:
      - name: pipeline-docker-registry
      containers:
      - name: maven
        image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
        ports:
        - containerPort: 8080
